import type { Metadata } from "next";
import localFont from "next/font/local";
import PageRenderLayout from "../layouts/PageRenderLayout";
import "../scss/main.scss";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "PRANTO SHIKDER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#3096fe" />

        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        {/* <meta
  name="apple-mobile-web-app-status-bar-style"
  content="#1A73E8"
/> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} scrollbar antialiased`}
        suppressHydrationWarning={true}
      >
        <PageRenderLayout>{children}</PageRenderLayout>
      </body>
    </html>
  );
}
